import Appbar from "./components/appbar/Appbar";
import { AuthProvider } from "./context/authClientContext";
import LayoutPages from "./layoutPages";
import "./tailwind.globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coca cola shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutPages>
          <AuthProvider>
            <main className="">
              {children}
              <Appbar />
            </main>
          </AuthProvider>
        </LayoutPages>
      </body>
    </html>
  );
}
